simple-bank:
  runner:
    active: true
  money-laundering:
    threshold: 2000

spring:
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE